version: "3.4"
services:
 vite_docker:
  image: node:18-alpine
  container_name: vite_docker
  entrypoint: /bin/sh
  ports:
    - 3000:3000
  working_dir: /app
  volumes:
    - type: bind
      source: ./
      target: /app
  tty: true